### ISSUE TITLE
i can't seem to search properly 

### ISSUE THREAD

**Issue by GigaGiorgadze** [RedberryInternship/movie-quotes-front-Domianidze#37]
![specificed tests](https://user-images.githubusercontent.com/75663118/186894463-70cd17c6-0a58-4049-85c2-0ffee54e2645.gif)
![normal search](https://user-images.githubusercontent.com/75663118/186894483-19acda6d-5aa5-4f00-8b5b-97e77a305b26.gif)
all of this quotes are added by this user if that makes diff, 
am I doing search wrong? somehow?

**Comment by Domianidze** [comment]
I am doing this with mongodb search and that searches only with full words. Is that a problem?

**Comment by GigaGiorgadze** [comment]
yes search with contains, not exact match
